# Create a new user
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@nat.local",
  "name": "Smith",
  "password": "1"
}


###

# Login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@nat.local",
  "password": "12"
}

###

# Change password
PATCH http://localhost:8080/api/auth/password HTTP/1.1
Content-Type: application/json

{
  "id": "659ee2d6fcc1855c1d5bcbd2",
  "oldPassword": "1",
  "newPassword": "12"
}

###

# Get user by ID
GET http://localhost:8080/api/auth/659ee2d6fcc1855c1d5bcbd2 HTTP/1.1

###
