# Get post by ID
GET http://localhost:3000/api/posts/1f896ca0-1e12-42b4-9772-29dc73c841e9 HTTP/1.1

###

# Get list of posts
GET http://localhost:3000/api/posts?pageSize=4&pageNumber=1 HTTP/1.1

###

# Create video post

POST http://localhost:3000/api/posts/video/ HTTP/1.1
Content-Type: application/json

{
  "author": "author_id",
  "status": "draft",
  "isRepost": false,
  "tags": [
    { "text": "a" },
    { "text": "b" }
  ],
  "content": {
    "title": "sample video",
    "url": "http://video/url"
  }
}

###

# Create text post

POST http://localhost:3000/api/posts/text/ HTTP/1.1
Content-Type: application/json

{
  "author": "text_author_id",
  "status": "draft",
  "isRepost": false,
  "tags": [
    { "text": "c" },
    { "text": "d" }
  ],
  "content": {
    "title": "text post title",
    "description": "text post desc",
    "text": "text post text content"
  }
}

###

# Create quote post

POST http://localhost:3000/api/posts/quote/ HTTP/1.1
Content-Type: application/json

{
  "author": "author_id",
  "status": "published",
  "isRepost": false,
  "tags": [
    { "text": "a" },
    { "text": "b" }
  ],
  "content": {
    "text": "quote text",
    "quoteAuthor": "Jason Statham"
  }
}

###

# Create photo post

POST http://localhost:3000/api/posts/photo/ HTTP/1.1
Content-Type: application/json

{
  "author": "authorId",
  "status": "draft",
  "isRepost": false,
  "tags": [
    { "text": "c" },
    { "text": "b" }
  ],
  "content": {
    "url": "http://my_photo_url.com/me.jpg"
  }
}

###

# Create link post

POST http://localhost:3000/api/posts/link/ HTTP/1.1
Content-Type: application/json

{
  "author": "author_identificator",
  "status": "draft",
  "isRepost": false,
  "tags": [
    { "text": "c" },
    { "text": "b" }
  ],
  "content": {
    "url": "https://www.wikipedia.org/",
    "description": "Wikipedia The Free Encyclopedia"
  }
}

###

# Update video post

PATCH http://localhost:3000/api/posts/1f896ca0-1e12-42b4-9772-29dc73c841e9 HTTP/1.1
Content-Type: application/json

{
  "status": "draft",
  "isRepost": false,
  "tags": [
    { "text": "c" },
    { "text": "d" },
    { "text": "e" }
  ]
}

###

# Delete post

DELETE http://localhost:3000/api/posts/1f89a3ae-7883-44c5-a1f8-1d0593b099b8 HTTP/1.1
